# Generated by Django 6.0.7 on 2026-07-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enrollment', models.IntegerField()),
                ('age', models.IntegerField()),
                ('department', models.CharField(max_length=100)),
            ],
        ),
    ]
